version: "3.3"
services:
  controller:
    image: 1646552/controller:latest
    container_name: "controller"
    ports:
      - "80:8000"
    networks:
      - internal
  welcome:
    image: 1646552/welcome:latest
    container_name: "welcome"
    ports:
      - "8001:8001"
    networks:
      - internal
networks:
  internal:


