version: "3"
services:
  controller:
    image: 1646552/controller:latest
    ports:
      - "8000:8000"
    networks:
      internal:
    depends_on:
      - welcome
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
  welcome:
    image: 1646552/welcome:latest
    ports:
      - "8001:8001"
    networks:
      internal:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
networks:
  internal: