version: "3"
services:
  controller:
    image: 1646552/controller:latest
    ports:
    - "8000:80"
    depends_on:
      - welcome
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s