version: "3.3"
services:
  controller:
    image: 1646552/controller:latest
    container_name: "controller"
    ports:
      - "80:8000"
    networks:
      - internal
    restart: unless-stopped
  welcome:
    image: 1646552/welcome:latest
    container_name: "welcome"
    ports:
      - "8001:8001"
    networks:
      - internal
    restart: unless-stopped
  entertainment:
    image: 1646552/entertainment:latest
    container_name: "entertainment"
    ports:
      - "8002:8002"
    networks:
      - internal
    restart: unless-stopped
  finances:
    image: 1646552/finances:latest
    container_name: "finances"
    ports:
      - "8003:8003"
    networks:
      - internal
    restart: unless-stopped
  journey:
    image: 1646552/journey:latest
    container_name: "journey"
    ports:
      - "8004:8004"
    networks:
      - internal
    restart: unless-stopped
networks:
  internal:


