

# from: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
  

name: Entertainment test and build

on:
  push:
    branches: [ main ]
    paths:
      - "entertainment/**"
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f entertainment/src/requirements.txt ]; then pip install -r entertainment/src/requirements.txt; fi
      - name: Inject environment file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_IMDB_KEY: ${{ secrets.IMDB_KEY }}
          envkey_X_AUTH_TOKEN: ${{ secrets.X_AUTH_TOKEN }}
          directory: entertainment/src
          file_name: .env
          fail_on_empty: false
      - name: Run tests
        run: |
          pytest entertainment/tests
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: entertainment
          push: true
          tags: 1646552/entertainment:latest
          labels: ${{ steps.meta.outputs.labels }}
